### ISSUE TITLE
I have created a German Localisation

### ISSUE THREAD

**Issue by Chaikobar** [Seicing/aoe4legion#1]
[de.csv](https://github.com/user-attachments/files/18195234/de.csv)
[de.xlsx](https://github.com/user-attachments/files/18195235/de.xlsx)

The translation template file was from the in-game mod manager in english. 
I extracted the Database-Document from the .sga File.

[aoe4legion_OriginalFiles as Reference.zip](https://github.com/user-attachments/files/18195318/aoe4legion_OriginalFiles.as.Reference.zip)

I would have liked to adapt this for my game, but to do that I would have to find out which tool you used to create the .ucs file  :D

Excel or NotePad++ does not support this format, but you can use the translation if you want :)

I saw the ModData when extracting the LocalisationFiles and can say this mod is a great work, 
and the new Gameplay-Content are the additions to the game that complete it

greets from Germany and merry Christmas to all

**Comment by Seicing** [comment]
Merry Christmas, Friend
Thank you for your support of this mod


Localization files use csv format, and the game will automatically convert to ucs format when it is packaged. In any case, it is best to open them with Visual Studio Code
There is a display plugin on vscode
https://marketplace.visualstudio.com/items?itemName=Janne252.relic-ucs


I plan to integrate the German version into the mod if possible
Finally, thank you again
&nbsp;


陛下
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月19日(星期四) 下午5:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Seicing/aoe4legion] I have created a German Localisation (Issue #1)














 
de.csv
 de.xlsx
 
The translation template file was from the in-game mod manager in english.
 I extracted the Database-Document from the .sga File.
 
aoe4legion_OriginalFiles as Reference.zip
 
I would have liked to adapt this for my game, but to do that I would have to find out which tool you used to create the .ucs file  :D
 
Excel or NotePad++ does not support this format, but you can use the translation if you want :)
 
I saw the ModData when extracting the LocalisationFiles and can say this mod is a great work,
 and the new Gameplay-Content are the additions to the game that complete it
 
greets from Germany and merry Christmas to all

**Comment by Seicing** [comment]
I added it to the project and made some formatting corrections. 
Thank you very much for your efforts.

**Comment by Chaikobar** [comment]
Thank you for your work on the mod, and the Link to the Plugin. I was searching for something like that
